<?php
/**
 * @file
 * Generates tables for developing the Twig table template.
 */

/**
 * Implements hook_menu().
 */
function twig_tables_menu() {
  $items['twig-tables'] = array(
    'title' => 'Twig tables',
    'page callback' => 'twig_tables_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function twig_tables_page() {
  $table1 = array(
    'rows' => array(
      array(
        array(
          'data' => t('Foo'),
          'header' => TRUE,
        ),
        t('Bar'),
        t('Baz'),
      ),
      array(
        array(
          'data' => t('Foo'),
          'header' => TRUE,
        ),
        t('Bar'),
        t('Baz'),
      ),
      array(
        array(
          'data' => t('Foo'),
          'header' => TRUE,
        ),
        t('Bar'),
        t('Baz'),
      ),
    ),
  );

  $build['table1'] = array(
    '#theme' => 'table',
    '#rows' => $table1['rows'],
    '#empty' => t('No rows defined.'),
    '#attributes' => array(
      'id' => 'twig-table1',
    ),
  );

  $table2 = array(
    'header' => array(
      t('Foo'),
      t('Bar'),
      array(
        'data' => array(
          '#theme' => 'html_tag',
          '#tag' => 'span',
          '#value' => t('Classes'),
        ),
        'class' => array(
          'baz-class',
          'baz-class',
        ),
      ),
    ),
    'rows' => array(
      array(t('Foo'), t('Bar'), t('Baz')),
      array(t('Foo'), t('Bar'), t('Baz')),
      array(t('Foo'), t('Bar'), t('Baz')),
      array(
        array(
          'data' => array(
            '#theme' => 'html_tag',
            '#tag' => 'span',
            '#value' => t('Classes and ID'),
          ),
          'class' => array(
            'foo-class',
          ),
          'id' => 'foo-id',
        ),
        t('Bar'),
        t('Baz'),
      ),
    ),
  );

  $build['table2'] = array(
    '#theme' => 'table',
    '#header' => $table2['header'],
    '#rows' => $table2['rows'],
    '#empty' => t('No rows defined.'),
    '#attributes' => array(
      'id' => 'twig-table2',
    ),
  );

  $table3 = array(
    'header' => array(
      t('Foo'),
      array('data' => t('Operations'), 'colspan' => '2'),
    ),
    'rows' => array(
      array(
        t('Bar'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
      array(
        t('Baz'),
        l(t('edit'), 'edit'),
        l(t('reset'), 'reset'),
      ),
    ),
  );

  $build['table3'] = array(
    '#theme' => 'table',
    '#header' => $table3['header'],
    '#rows' => $table3['rows'],
    '#sticky' => TRUE,
  );

  $table4 = array(
    'header' => array(
      array('data' => t('Numbers'), 'field' => 't.numbers'),
      array('data' => t('Letters'), 'field' => 't.alpha'),
      array('data' => t('Mixture'), 'field' => 't.random'),
    ),
  );

  $query = db_select('twig_tables_sorting', 't')
    ->extend('Drupal\Core\Database\Query\TableSortExtender');
  $query->fields('t');
  $result = $query->orderByHeader($table4['header'])->execute();

  $table4['rows'] = array();
  foreach ($result as $row) {
    $table4['rows'][] = array('data' => (array) $row);
  }

  $build['table4'] = array(
    '#theme' => 'table',
    '#header' => $table4['header'],
    '#rows' => $table4['rows'],
  );

  // add colgroup examples
  $build += twig_tables_colgroup_tests();
  return $build;
}


function twig_tables_colgroup_tests() {
  // Default D7 example in docs 
  $colgroups1 = array(
    // COLGROUP with one COL element.
    array(
      array(
        'class' => array('funky'), // Attribute for the COL element.
      ),
    ),
    // Colgroup with attributes and inner COL elements.
    array(
      'data' => array(
        array(
          'class' => array('funky'), // Attribute for the COL element.
        ),
      ),
      'class' => array('jazzy'), // Attribute for the COLGROUP element.
    ),
  );


  $colgroups2 = array(
    array(
      array('class' => array('cg1c1')),
    ),
    array(
      'class' => array('cg2'),
      'data' => array(
        array('class' => array('cg2c1')),
        array('class' => array('cg2c2')),
      ), 
    ),
    array(
      'class' => array('cg3'),
      'data' => array(
        array('class' => array('cg3c1')),
        array('class' => array('cg3c2')),
        array('class' => array('cg3c3')),
        array('class' => array('cg3c4')),
      ),
    ),
  );

  $colgroups3 = array(
    array(
        array('class' => array('cg2c1')),
        array(),
    ),
    array(
      'class' => array('cg2'),
      'data' => array(
        array('class' => array('cg2c1')),
        array('class' => array('cg2c2')),
      ), 
    ),
    array(
      'class' => array('cg3'),
    ),
  );

  $base_table = array(
    '#theme' => 'table',
    '#caption' => 'Colgroup Examples',
    '#colgroups' => array(),
    '#header' => array(
      t('Foo'),
      array('data' => t('Operations'), 'colspan' => '2'),
      'test'
    ),
    '#empty' => t('No rows defined.'),
    '#attributes' => array(
      'id' => 'twig-table2',
    ),
    '#rows' => array(
      array(
        t('Bar'),
        l(t('ipsum'), 'lorem'),
        l(t('lorem'), 'ipsum'),
        'Biz'
      ),
      array(
        t('Baz'),
        l(t('ipsum'), 'lorem'),
        l(t('lorem'), 'ipsum'),
        'Buzz'
      ),
    ),
  );

  $tables = array();
  $tables['colgroup1'] = $base_table;
  $tables['colgroup2'] = $base_table;
  $tables['colgroup3'] = $base_table;
  $tables['colgroup1']['#colgroups'] = $colgroups1;
  $tables['colgroup2']['#colgroups'] = $colgroups2;
  $tables['colgroup3']['#colgroups'] = $colgroups3;


  return $tables;

}

